### ISSUE TITLE
Mask recommendations

### ISSUE THREAD

**Issue by Amylala12** [TomMakesThings/Bluetooth-Wrench-Mask#1]
Hey - sorry to bother. But I'm not sure what mask to buy from amazon uk, any recommendations?

**Comment by TomMakesThings** [comment]
Sure, the one named "Xunfee Steampunk Mask Adult Watchdog Punk Goth Rivet Face Masks Grim Reaper Mask for Halloween Party Decoration Cosplay Costume Prop" is the same make as the one I used. Sometimes you can find it for less by searching for some of the same tags they use in the name. Alternatively if you're willing to wait a month for one to arrive, you can find them on Aliexpress too.

**Comment by Amylala12** [comment]
Thank you so much!
