### ISSUE TITLE
Weird Matrix Behavior

### ISSUE THREAD

**Issue by Juls-Hg** [TomMakesThings/Bluetooth-Wrench-Mask#2]
Hey man. Love and really appreciate the project.
I just bought all the parts and now, for some reason, each Matrix-Module works on it's own but when daisy chained, like you show in your wiring diagram, module 1 just illuminates the first row and Module 2 works alright except for a custom pattern, then it sometimes cuts out the bottom two rows with no traceable pattern. it does get itself together after a refresh rarely.
Bluetooth is working flawlessly, even tho i had to wire it up myself since you forgot that in the documentation.
I have zero coding knowledge so any help is appreciated ^^'

**Comment by TomMakesThings** [comment]
Hi, I'm glad you like it and are giving it a go! It's been a while since I made this project and unfortunately do not have the parts with me to test anything out myself. It could be that the board is not getting enough power to light up both matrices at once. I'd recommend testing it plugged in to a computer and with different / fresh batteries to see if this makes a difference. If you're still are having issues, I'd try find a tutorial with some simple pre-written code that lights up chained matrices and see if it works then to rule out issues with chaining.

**Comment by TomMakesThings** [comment]
You're right that I forgot to include the Bluetooth wiring, thanks for pointing that out. As for the custom pattern sometimes skipping rows, I have observed this too occasionally. I suspect it is an overflow problem where the bluetooth receiver is not able to pick up all of the signal sent to it and the board runs out of memory, e.g. if it is also picking up background signals or sent too many requests in a short period of time. This is something I was meant to look at and never got round to it, so apologies for that! Though it may be possible to increase the receiver buffer size in the code uploaded to the board.

**Comment by Juls-Hg** [comment]
nah don't worry. it's been more of an oddity i found by accident. gotta try every feature to know how and if it works yk ^^
that one isn't critical to me. overall working is my need ^^'

the behavior is the same on a new-ish battery and via usb. i flipped modules, ICs, cables, tried other matrixes. it may be the PCBs/SMDs but i believe that to be unrelistic. by now i even tried to compile and upload with the old IDE (v1.8.19 instead of v2.3.2) to rule out any compiling issue. 
Sidenote: I plugged it together with a different matrix (red) now and it worked. i then tested all of my matrixes i have (4 white, 2 red) and after cycling them it didn't work again with the one it worked before. mentioning i have no clue what is going on is an understatement x'D

but thanks already for the quick reply <3


edit: i tried [these](https://xantorohara.github.io/led-matrix-editor/) examples and they did not work. just lightend up the uppest line and weirdly flashing the white matrixes. the reds just light up the line

**Comment by TomMakesThings** [comment]
Oh that's strange. What you've described sounds like a hardware issue over a problem with the code. Though with the example you've given, did you change the variables at the top to match the matrix pins? e.g. `const int DIN_PIN = 7;` is different from the pin given in the tutorial where DIN for matrix one is linked to pin 12.

**Comment by Juls-Hg** [comment]
yes i adjusted pins

maybe i have to return the boards then, thankfully i have a right to return here in germany

**Comment by TomMakesThings** [comment]
That's a pain, though lucky you can return parts. The example you gave is essentially a cut down version of the code I wrote, so a good way to test it at least. I haven't got any other suggestions, but good luck with it!

**Comment by Juls-Hg** [comment]
thank you so much still, i'll chime in again once i get it to work

**Comment by Juls-Hg** [comment]
Yeah so here's the update.
A new matrix board just arrived today free of charge yet the behavoir stays.
I guess unless I pigtail the cables I have to cancel the project. Since I'm invested in it so deep already I'll look into that. sad for some missing functionality but at least i (maybe) have it lighting up

**Comment by Juls-Hg** [comment]
I GOT IT
The devil's in the detail! Your wiring diagram shows Pin 8 as a ground connection.
I hooked it to a designated ground point and now it works!!
I just did it out of curiosity since pigtailing the connections didn't work. I looked at it and just thought "huh. does being on a whatever-pin™ instead of a designated ground affect it?" and BOOM.
Man I'm so happy but also curse you xD (yk)

**Comment by TomMakesThings** [comment]
Good find and thank you for being so persistent! Hopefully the reward of an awesome Wrench mask is worth the pain haha. 

I definitely need to update that diagram. I found an old and slightly rubbish picture of my Ardunio wiring. The mix up is because I was using an orange wire at pin 8 for a prototype using an IR sensor.

![Ardunio_Wiring](https://github.com/TomMakesThings/Bluetooth-Wrench-Mask/assets/61354833/fdb82386-de4b-47ea-bdda-b9f9b3390c8a)

**Comment by Juls-Hg** [comment]
yess, such a relieve. now i just have to glue everything into the mask in a way that i can still see and breathe :D (smiles through the pain)
and I'll add some padding around the forhead, nasal bone and chin.

after all thank you for the groundwork and all the help. do you have paypal, ko-fi or something to tip at?

**Comment by TomMakesThings** [comment]
Good luck with the next steps! I've been able to wear mine for quite a long time at events before needing to take it off. Visibility isn't great, but you'll get a lot of attention. I would also recommend making sure you have enough elastic or alternative support as the components are quite heavy. I added two straps to mine to hold it up.

Thanks for the offer of the tip! If you want to leave one I have a [ko-fi page](https://ko-fi.com/tommakesthings). Though honestly your debugging has been very helpful so up to you.

**Comment by Juls-Hg** [comment]
thanks <3
yeah as a cosplayer you're always an attention whore so i hope this will get attention xD
in the future i may add the original vest since for now it's too expensive for me (>150$)
i'll fix the battery box and uno to the hairband so the weight is more distributed and i can be cheeky with the wiring. not trying to bodge it, more to make it a bit more clean. cable management is important after all ;)

troubleshooting was painful yeah but your work still deserves something. I value work and effort. maker support maker after all
making documentation for something like this is a very time consuming task and often overlooked
